os:
  - linux
language: java
jdk:
  - oraclejdk10
env:
  - GOPATH="/tmp" GAUGE_ROOT="/tmp/gauge" GAUGE_TELEMETRY_ENABLED=false
before_install:
  - wget https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz
  - sudo tar -xvf go1.7.4.linux-amd64.tar.gz
  - sudo mv go /usr/local
  - export GOROOT=/usr/local/go
  - export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
  - go get github.com/tools/godep
install:
  - go run make.go
script: 
  - go version
  - cd ..
  - git clone --depth=1 https://github.com/getgauge/gauge-tests
  - cd gauge-tests
  - GAUGE_PREFIX=/tmp ./install_latest_gauge_nightly.sh
  - gauge -v
  - echo "gauge_repository_url = https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master/" >> ~/.gauge/config/gauge.properties
  - export PATH=/tmp/bin:$PATH
  - cd $TRAVIS_BUILD_DIR
  - go run make.go --install
  - cd ..
  - cd gauge-tests
  - gauge install
  - gauge -v
  - ./starttests.sh java